from django import template
from django.utils.safestring import mark_safe


register = template.Library()

TABLE_HEAD = """
                <table class="product-main__table">
                  <tbody>
             """

TABLE_TAIL = """
                  </tbody>
                </table>
             """

TABLE_CONTENT = """
                    <tr class="product-main__row">
                      <td class="product-main__col">{name}</td>
                      <td class="product-main__col">{value}</td>
                    </tr>
                """

PRODUCT_SPEC = {
    'notebook': {
        'Дата выхода на рынок': 'market_date',
        'Продуктовая линейка': 'product_line',
        'Тип': 'type',
        'Назначение': 'appointment',
        'Процессор': 'cpu',
        'Модель процессора': 'model_cpu',
        'Количество ядер': 'number_of_cores',
        'Количество потоков': 'number_of_threads',
        'Тактовая частота': 'clock_frequency',
        'Turbo-частота': 'turbo_frequency',
        'Энергопотребление процессора': 'cpu_power_consumption',
        'Встроенная в процессор графика': 'processor_graphics',
        'Материал корпуса': 'body_material',
        'Цвет корпуса': 'body_color',
        'Материал крышки': 'cover_material',
        'Цвет крышки': 'cover_color',
        'Подсветка корпуса': 'body_backlight',
        'Защищенный корпус': 'body_protected',
        'Ширина': 'width',
        'Глубина': 'depth',
        'Толщина': 'thickness',
        'Вес': 'weight',
        'Диагональ экрана': 'screen_diagonal',
        'Разрешение экрана': 'screen_resolution',
        'Частота матрицы': 'matrix_frequency',
        'Технология экрана': 'screen_technology',
        'Яркость экрана': 'screen_brightness',
        'Поверхность экрана': 'screen_surface',
        'Экран': 'screen',
        'Тип оперативной памяти': 'ram_type',
        'Частота оперативной памяти': 'ram_frequency',
        'Объём памяти': 'ram_volume',
        'Максимальный объём памяти': 'max_ram_volume',
        'Всего слотов памяти': 'total_memory_slots',
        'Свободных слотов памяти': 'free_memory_slots',
        'Конфигурация накопителя': 'drive_configuration',
        'Тип накопителя': 'drive_type',
        'Ёмкость накопителя': 'drive_volume',
        'Модель видеокарты': 'graphics_card_model',
        'Локальная видеопамять': 'local_video_memory',
        'Камера': 'camera',
        'Основная камера': 'main_cam',
        'Встроенный микрофон': 'microphone',
        'Встроенные динамики': 'speakers',
        'Цифровое поле': 'digital_field',
        'Управление курсором': 'cursor_control',
        'NFC': 'nfc',
        'Bluetooth': 'bluetooth',
        'LAN': 'lan',
        'Wi-Fi': 'wifi',
        'Всего USB Type A': 'usb_type_a',
        'USB 2.0': 'usb_2',
        'USB 3.2 Gen1 Type-A': 'usb_32_gen1_a',
        'USB 3.2 Gen2 Type-A': 'usb_32_gen2_a',
        'Всего USB Type C': 'usb_type_c',
        'USB 3.2 Gen1 Type-C': 'usb_32_gen1_c',
        'USB 3.2 Gen2 Type-C': 'usb_32_gen2_c',
        'USB 3.2 Gen 2x2': 'usb_32_gen2x2',
        'USB4': 'usb4',
        'Максимальная скорость передачи данных USB': 'maximum_baud_rate_usb',
        'HDMI': 'hdmi',
        'Аудио выходы': 'audio_outputs',
        'Запас энергии': 'energy_reserve',
        'Время работы': 'working_hours',
        'Зарядка ноутбука через USB Type-C': 'charge_via_type_c',
        'Адаптер питания USB-C': 'power_adapter_usb_c',
        'Быстрая зарядка': 'fast_charging',
        'Операционная система': 'operating_system'
    },
    'smartphone': {
        'Дата выхода на рынок': 'market_date',
        'Тип': 'type',
        'Операционная система': 'operating_system',
        'Версия операционной системы': 'version_operating_system',
        'Размер экрана': 'screen_size',
        'Разрешение экрана': 'screen_resolution',
        'Оперативная память': 'ram',
        'Флэш-память': 'flash_memory',
        'Количество основных камер': 'number_of_main_cameras',
        'Количество точек матрицы': 'number_of_matrix_points',
        'Количество SIM-карт': 'number_of_sim',
        'Формат SIM-карты': 'format_of_sim',
        'Максимальное разрешение видео': 'max_video_resolution',
        'Поддержка карт памяти': 'memory_card_support',
        'Платформа': 'platform',
        'Процессор': 'cpu',
        'Тактовая частота процессора': 'clock_frequency_cpu',
        'Количество ядер': 'number_of_cores',
        'Разрядность процессора': 'cpu_size',
        'Техпроцесс': 'technical_process',
        'Графический ускоритель': 'graphics_accelerator',
        'Частота ГПУ': 'gpu_frequency',
        'Конструкция корпуса': 'body_design',
        'Материал корпуса': 'body_material',
        'Материал задней крышки': 'back_cover_material',
        'Цвет корпуса': 'body_color',
        'Цвет фронтальной панели': 'front_cover_color',
        'Расположение фронтальной камеры': 'front_camera_location',
        'Расположение сканера отпечатка пальца': 'fingerprint_reader_location',
        'Ширина': 'width',
        'Глубина': 'depth',
        'Толщина': 'thickness',
        'Вес': 'weight',
        'Технология экрана': 'screen_technology',
        'Количество цветов экрана': 'number_of_screen_colors',
        'Разрешающая способность экрана': 'screen_ability_resolution',
        'Соотношение сторон': 'aspect_ratio',
        'Частота обновления экрана': 'screen_refresh_rate',
        'Сенсорный экран': 'touch_screen',
        'Защита от царапин': 'scratch_protection',
        'Встроенная вспышка': 'built_in_flash',
        'Автоматическая фокусировка': 'auto_focus',
        'Оптическая стабилизация': 'optical_stabilization',
        'Максимальное количество кадров в секунду': 'max_fps',
        'Фронтальная камера': 'front_camera',
        'Стереодинамики': 'stereo_speakers',
        'Сканер отпечатка пальца': 'fingerprint_reader',
        'Разблокировка по лицу': 'face_unlock',
        'ИК-передатчик': 'ir_transmitter',
        'FM-приёмник': 'fm_receiver',
        'Беспроводная зарядка': 'wireless_charger',
        'Быстрая зарядка': 'fast_charging',
        'Акселерометр': 'accelerometer',
        'Гироскоп': 'gyroscope',
        'Датчик освещенности': 'light_sensor',
        'Барометр': 'barometer',
        'ANT+': 'ant',
        'GPS': 'gps',
        'ГЛОНАСС': 'glonass',
        'Beidou': 'beidou',
        'EDGE': 'edge',
        'HSPA': 'hspa',
        'HSPA+': 'hspa_plus',
        'LTE': 'lte',
        '5G': 'g5',
        'Bluetooth': 'bluetooth',
        'Аудиовыход': 'audio_output',
        'Wi-Fi': 'wifi',
        'Разъём подключения': 'connection_socket',
        'NFC': 'nfc',
        'Тип аккумулятора': 'battery_type',
        'Емкость аккумулятора': 'battery_capacity'
    },
    'smartwatch': {
        'Дата выхода на рынок': 'market_date',
        'Флэш-память': 'flash_memory',
        'Встроенная камера': 'built_in_camera',
        'Тип': 'type',
        'Поддержка платформ': 'platform_support',
        'Материал корпуса': 'body_material',
        'Цвет корпуса': 'body_color',
        'Встроенный музыкальный плеер': 'built_in_music_player',
        'Звонки': 'calls',
        'Голосовое управление': 'voice_control',
        'Дистанционное управление': 'remote_control',
        'Бесконтактные платежи': 'contactless_payments',
        'Вибрация': 'vibration',
        'Ширина': 'width',
        'Глубина': 'depth',
        'Толщина': 'thickness',
        'Вес': 'weight',
        'Размеры браслета': 'bracelet_size',
        'Технология экрана': 'screen_technology',
        'Количество цветов экрана': 'number_of_screen_colors',
        'Размер экрана': 'screen_size',
        'Разрешение экрана': 'screen_resolution',
        'Разрешающая способность экрана': 'screen_ability_resolution',
        'Сенсорный экран': 'touch_screen',
        'Защита от царапин': 'scratch_protection',
        'Акселерометр': 'accelerometer',
        'Гироскоп': 'gyroscope',
        'Датчик освещенности': 'light_sensor',
        'Барометр': 'barometer',
        'Шагомер': 'pedometer',
        'Пульсометр': 'heart_rate',
        'Датчик ЭКГ': 'ecg_sensor',
        'Компас': 'compass',
        'Глубиномер': 'depth_gauge',
        'GPS': 'gps',
        'ГЛОНАСС': 'glonass',
        'Bluetooth': 'bluetooth',
        'Аудиовыход': 'audio_output',
        'Wi-Fi': 'wifi',
        'USB': 'usb',
        'NFC': 'nfc',
        'Тип аккумулятора': 'battery_type',
        'Емкость аккумулятора': 'battery_capacity',
        'Время работы': 'working_hours',
        'Беспроводная зарядка': 'wireless_charger'
    },
    'ebook': {
        'Дата выхода на рынок': 'market_date',
        'Размер экрана': 'screen_size',
        'Тип экрана': 'screen_type',
        'Технология экрана': 'screen_technology',
        'Разрешение экрана': 'screen_resolution',
        'Версия операционной системы': 'os_version',
        'Оперативная память': 'ram',
        'Флэш-память': 'flash_memory',
        'Встроенная камера': 'built_in_camera',
        'Материал корпуса': 'body_material',
        'Цвет корпуса': 'body_color',
        'Ширина': 'width',
        'Длина': 'length',
        'Толщина': 'thickness',
        'Вес': 'weight',
        'Сенсорный экран': 'touch_screen',
        'Подсветка экрана': 'screen_backlight',
        'Поддержка текстовых форматов': 'support_txt_format',
        'Поддержка фото форматов': 'support_photo_format',
        'Поддержка аудио форматов': 'support_audio_format',
        'Поддержка архивов': 'support_archive',
        'Поддержка видео форматов': 'support_video_format',
        'Поддержка карт памяти': 'memory_card_support',
        'Запись звука': 'sound_recording',
        'Встроенный динамик': 'built_in_speaker',
        'Встроенный микрофон': 'built_in_microphone',
        'Bluetooth': 'bluetooth',
        'Аудиовыход': 'audio_output',
        'Wi-Fi': 'wifi',
        '3G-модем': 'modem_3g',
        'USB': 'usb',
        'Тип аккумулятора': 'battery_type',
        'Емкость аккумулятора': 'battery_capacity',
        'Время автономной работы': 'battery_life',
        'Время зарядки': 'charging_time'
    },
    'tv': {
        'Дата выхода на рынок': 'market_date',
        'Тип': 'type',
        'Диагональ экрана': 'screen_diagonal',
        'Разрешение экрана': 'screen_resolution',
        'Частота матрицы': 'matrix_frequency',
        'Изогнутый экран': 'curved_screen',
        'Поддержка 3D': 'support_3d',
        'Индекс качества изображения': 'image_quality_index',
        'Smart TV': 'smart_tv',
        'Платформа Smart TV': 'smart_tv_platform',
        'Версия системы': 'system_version',
        'Безрамочный дизайн': 'frameless_design',
        'Цвет корпуса': 'body_color',
        'Цвет рамки': 'frame_color',
        'Цвет подставки': 'stand_color',
        'Тип матрицы': 'matrix_type',
        'Глубина цвета': 'color_depth',
        'Локальное затемнение': 'local_dimming',
        'Расширенный динамический диапазон (HDR)': 'hdr',
        'Расширенная цветовая палитра': 'extended_color_palette',
        'Процессор': 'cpu',
        'Голосовое управление': 'voice_control',
        'ТВ-тюнер': 'tv_tuner',
        'Сабвуфер': 'subwoofer',
        'Мощность звуковой системы': 'sound_system_power',
        'Поддержка HDMI eARC': 'hdmi_support',
        'Bluetooth': 'bluetooth',
        'Wi-Fi': 'wifi',
        'HDMI': 'hdmi',
        'Версия HDMI': 'hdmi_version',
        'Цифровой выход S/PDIF': 'digital_output',
        'Выход на наушники': 'headphone_out',
        'USB': 'usb',
        'Ethernet': 'ethernet',
        'AirPlay': 'airplay',
        'Smart-пульт': 'smart_console',
        'Ширина': 'width',
        'Высота (с учетом подставки)': 'height_plus',
        'Глубина(с учетом подставки)': 'depth',
        'Высота (без подставки)': 'height',
        'Толщина панели': 'thickness',
        'Вес (с подставкой)': 'weight_plus',
        'Вес (без подставки)': 'weight'
    },
    'mouse': {
        'Интерфейс подключения мыши': 'connection_interface',
        'Тип': 'type',
        'Назначение': 'appointment',
        'Размер мыши': 'size',
        'Тип сенсора': 'sensor_type',
        'Модель сенсора': 'sensor_model',
        'Максимальное разрешение сенсора': 'max_sensor_resolution',
        'Максимальная частота опроса': 'max_polling_rate',
        'Материал корпуса': 'body_material',
        'Подсветка': 'backlight',
        'Цвет': 'color',
        'Длина провода': 'wire_length',
        'Изменяемое разрешение': 'variable_resolution',
        'Встроенная память': 'built_in_memory',
        'Время отклика': 'response_time',
        'Количество кнопок': 'number_of_buttons',
        'Количество колёс прокрутки': 'number_of_scroll_wheels',
        'Тип колеса прокрутки': 'scroll_wheel_type',
        'Оплетка провода': 'wire_braid',
        'Тихий клик': 'quiet_click',
        'Ширина': 'width',
        'Длина': 'length',
        'Высота': 'height',
        'Вес': 'weight'
    },
    'keyboard': {
        'Дата выхода на рынок': 'market_date',
        'Тип': 'type',
        'Технология переключателя': 'switch_technology',
        'Назначение': 'appointment',
        'Цвет': 'color',
        'Интерфейс подключения клавиатуры': 'connection_interface',
        'Цифровой блок': 'digital_block',
        'Длина провода': 'wire_length',
        'Материал корпуса': 'body_material',
        'Дополнительные кнопки': 'additional_buttons',
        'Форма клавиш': 'key_shape',
        'Тип переключателя': 'switch_type',
        'Встроенная память': 'built_in_memory',
        'Подсветка клавиш': 'key_illumination',
        'Оплетка провода': 'wire_braid',
        'USB-порт': 'usb',
        'Аудиовход': 'audio_input',
        'Аудиовыход': 'audio_output',
        'Ширина': 'width',
        'Глубина': 'depth',
        'Толщина': 'thickness',
        'Вес': 'weight'
    },
    'mat': {
        'Совместимость': 'compatibility',
        'Материал поверхности': 'material',
        'Цвет': 'color',
        'Бортик': 'sideboard',
        'Функциональные особенности': 'functional_features',
        'Длина кабеля': 'cable_length',
        'Ширина': 'width',
        'Глубина': 'depth',
        'Толщина': 'thickness',
    },
    'microphone': {
        'Тип': 'type',
        'Назначение': 'appointment',
        'Вид': 'view',
        'Беспроводной интерфейс': 'wireless_interface',
        'Материал корпуса': 'body_material',
        'Поп-фильтр': 'pop_filter',
        'Разъем(-ы) на микрофоне': 'microphone_jack',
        'Разъем(-ы) подключения': 'connector',
        'Цвет': 'color',
        'Направленность': 'focus',
        'Изменяемая направленность': 'variable_focus',
        'Частота дискретизации': 'sampling_frequency',
        'Нижняя граница частотного диапазона': 'bottom_frequency_range_boundary',
        'Верхняя граница частотного диапазона': 'top_frequency_range_boundary',
        'Диаметр диафрагмы': 'diaphragm_diameter',
        'Соотношение сигнал/шум': 'signal_to_noise_ratio',
        'Чувствительность': 'sensitivity',
        'Макс. уровень звукового давления (SPL)': 'spl',
        'Коэф. гармонических искажений': 'coefficient_harmonic_distortion',
        'Индикация на микрофоне': 'microphone_indication',
        'Длина кабеля': 'cable_length',
        'Выход на наушники': 'headphone_out',
        'Элементы управления': 'control_elements',
        'Питание микрофона': 'microphone_power',
        'Подсветка': 'backlight',
        'USB для периферии': 'usb',
        'Цифровые эффекты': 'digital_effects',
        'Вес': 'weight'
    },
    'tablet': {
        'Дата выхода на рынок': 'market_date',
        'Назначение': 'appointment',
        'Диагональ экрана': 'screen_diagonal',
        'Разрешение экрана': 'screen_resolution',
        'Матрица экрана': 'screen_matrix',
        'Операционная система': 'os',
        'Версия операционной системы': 'version_operating_system',
        'Процессор': 'cpu',
        'Графический ускоритель': 'graphics_accelerator',
        'Оперативная память': 'ram',
        'Внутренняя память': 'inner_memory',
        'Поддержка нескольких SIM-карт': 'multiple_sim_support',
        'Голосовые вызовы': 'voice_calls',
        'Количество ядер': 'number_of_cores',
        'Тактовая частота': 'clock_frequency',
        'Turbo-частота': 'turbo_frequency',
        'Материал корпуса': 'body_material',
        'Цвет корпуса': 'body_color',
        'Вибрация': 'vibration',
        '3D-экран': 'screen_3d',
        'Карты памяти': 'memory_cards',
        'Камера': 'camera',
        'Основная камера': 'main_cam',
        'Максимальное разрешение видео': 'max_video_resolution',
        'Авто-фокус': 'auto_focus',
        'Фронтальная камера': 'front_camera',
        'Встроенный микрофон': 'microphone',
        'Встроенные динамики': 'speakers',
        'Сканер отпечатка пальца': 'fingerprint_reader',
        'FM-тюнер': 'fm_tuner',
        'Акселерометр': 'accelerometer',
        'Гироскоп': 'gyroscope',
        'Датчик освещенности': 'light_sensor',
        'Разблокировка по лицу': 'face_unlock',
        'Барометр': 'barometer',
        'Датчик приближения': 'proximity_sensor',
        'Сканер LiDAR': 'lidar',
        'GPS/A-GPS': 'gps',
        'Электронный компас': 'compass',
        'MHL': 'mhl',
        'NFC': 'nfc',
        'Bluetooth': 'bluetooth',
        'ИК-порт': 'ir_port',
        'Wi-Fi': 'wifi',
        'Сотовая связь': 'cellular',
        'USB-C': 'usb_c',
        'HDMI': 'hdmi',
        'Аудиовыход': 'audio_output',
        'Емкость аккумулятора': 'battery_capacity',
        'Запас энергии': 'energy_reserve',
        'Время работы': 'working_hours',
        'Беспроводная зарядка': 'wireless_charger',
        'Ширина': 'width',
        'Длина': 'length',
        'Толщина': 'thickness',
        'Вес': 'weight'
    }
}


def get_product_spec(product, model_name):
    table_content = ''
    for name, value in PRODUCT_SPEC[model_name].items():
        table_content += TABLE_CONTENT.format(name=name, value=getattr(product, value))
    return table_content


@register.filter
def product_spec(product):
    model_name = product.__class__._meta.model_name
    return mark_safe(TABLE_HEAD + get_product_spec(product, model_name) + TABLE_TAIL)
