# Generated by Django 3.2.5 on 2021-07-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
