# Generated by Django 3.2.5 on 2021-07-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210723_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='in_orders',
            new_name='in_order',
        ),
    ]
