# Generated by Django 3.2.6 on 2021-08-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='processor_freq',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='time_without_charge',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='video',
        ),
        migrations.AddField(
            model_name='notebook',
            name='appointment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='audio_outputs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудио выходы'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='body_backlight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсветка корпуса'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='body_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет корпуса'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='body_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='body_protected',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Защищенный корпус'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='camera',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Камера'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='charge_via_type_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зарядка ноутбука через USB Type-C'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='clock_frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тактовая частота'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cover_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет крышки'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cover_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал крышки'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cpu_power_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Энергопотребление процессора'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='cursor_control',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Управление курсором'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='digital_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цифровое поле'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='drive_configuration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Конфигурация накопителя'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='drive_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип накопителя'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='drive_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ёмкость накопителя'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='energy_reserve',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Запас энергии'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Быстрая зарядка'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='free_memory_slots',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Свободных слотов памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='graphics_card_model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель видеокарты'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='hdmi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='lan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LAN'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='local_video_memory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локальная видеопамять'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='main_cam',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Основная камера'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='market_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='matrix_frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота матрицы'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='max_ram_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объём памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='maximum_baud_rate_usb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальная скорость передачи данных USB'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='microphone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенный микрофон'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='model_cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель процессора'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='nfc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NFC'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='number_of_cores',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество ядер'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='number_of_threads',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество потоков'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='power_adapter_usb_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адаптер питания USB-C'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='processor_graphics',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная в процессор графика'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='product_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Продуктовая линейка'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота оперативной памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип оперативной памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='ram_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объём памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Экран'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_brightness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Яркость экрана'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_diagonal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагональ экрана'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_surface',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поверхность экрана'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='screen_technology',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология экрана'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='speakers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенные динамики'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='thickness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Толщина'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='total_memory_slots',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Всего слотов памяти'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='turbo_frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Turbo-частота'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB4'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 2.0'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_32_gen1_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 3.2 Gen1 Type-A'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_32_gen1_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 3.2 Gen1 Type-C'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_32_gen2_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 3.2 Gen2 Type-A'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_32_gen2_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 3.2 Gen2 Type-C'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_32_gen2x2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB 3.2 Gen 2x2'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_type_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Всего USB Type A'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='usb_type_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Всего USB Type C'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='wifi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы'),
        ),
    ]
