# Generated by Django 3.2.6 on 2021-08-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_notebook_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='accum_volume',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='diagonal',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='display_type',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='frontal_cam_mp',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='main_cam_mp',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sd',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume_max',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='accelerometer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Акселерометр'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ant',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ANT+'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Соотношение сторон'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='audio_output',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудиовыход'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='auto_focus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Автоматическая фокусировка'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='back_cover_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал задней крышки'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='barometer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Барометр'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Емкость аккумулятора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='battery_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип аккумулятора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='beidou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beidou'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='body_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет корпуса'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='body_design',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Конструкция корпуса'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='body_material',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='built_in_flash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная вспышка'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='clock_frequency_cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тактовая частота процессора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='connection_socket',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разъём подключения'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='cpu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='cpu_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрядность процессора'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='edge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='EDGE'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='face_unlock',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разблокировка по лицу'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Быстрая зарядка'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='fingerprint_reader',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сканер отпечатка пальца'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='fingerprint_reader_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расположение сканера отпечатка пальца'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='flash_memory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Флэш-память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='fm_receiver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FM-приёмник'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='format_of_sim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат SIM-карты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_camera',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_camera_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расположение фронтальной камеры'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_cover_color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет фронтальной панели'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='g5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='5G'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='glonass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЛОНАСС'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='gps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='gpu_frequency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота ГПУ'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='graphics_accelerator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Графический ускоритель'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='gyroscope',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гироскоп'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='hspa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HSPA'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='hspa_plus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HSPA+'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ir_transmitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИК-передатчик'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='light_sensor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Датчик освещенности'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='lte',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LTE'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='market_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='max_fps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальное количество кадров в секунду'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='max_video_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальное разрешение видео'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='memory_card_support',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка карт памяти'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='nfc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='NFC'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_cores',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество ядер'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_main_cameras',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество основных камер'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_matrix_points',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество точек матрицы'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_screen_colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество цветов экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='number_of_sim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество SIM-карт'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='optical_stabilization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оптическая стабилизация'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='scratch_protection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Защита от царапин'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_ability_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешающая способность экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_refresh_rate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота обновления экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешение экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_technology',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология экрана'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='stereo_speakers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стереодинамики'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='technical_process',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Техпроцесс'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='thickness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Толщина'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='touch_screen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сенсорный экран'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='version_operating_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Версия операционной системы'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='wifi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='wireless_charger',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Беспроводная зарядка'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Оперативная память'),
        ),
    ]
