# Generated by Django 3.2.6 on 2021-08-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210811_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartwatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('market_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок')),
                ('flash_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Флэш-память')),
                ('built_in_camera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная камера')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('platform_support', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка платформ')),
                ('body_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса')),
                ('body_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет корпуса')),
                ('built_in_music_player', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенный музыкальный плеер')),
                ('calls', models.CharField(blank=True, max_length=255, null=True, verbose_name='Звонки')),
                ('voice_control', models.CharField(blank=True, max_length=255, null=True, verbose_name='Голосовое управление')),
                ('remote_control', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дистанционное управление')),
                ('contactless_payments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бесконтактные платежи')),
                ('vibration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вибрация')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('depth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубина')),
                ('thickness', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толщина')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('bracelet_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры браслета')),
                ('screen_technology', models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология экрана')),
                ('number_of_screen_colors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество цветов экрана')),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер экрана')),
                ('screen_resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешение экрана')),
                ('screen_ability_resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешающая способность экрана')),
                ('touch_screen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сенсорный экран')),
                ('scratch_protection', models.CharField(blank=True, max_length=255, null=True, verbose_name='Защита от царапин')),
                ('accelerometer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Акселерометр')),
                ('gyroscope', models.CharField(blank=True, max_length=255, null=True, verbose_name='Гироскоп')),
                ('light_sensor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Датчик освещенности')),
                ('barometer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Барометр')),
                ('pedometer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шагомер')),
                ('heart_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пульсометр')),
                ('ecg_sensor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Датчик ЭКГ')),
                ('compass', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компас')),
                ('depth_gauge', models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубиномер')),
                ('gps', models.CharField(blank=True, max_length=255, null=True, verbose_name='GPS')),
                ('glonass', models.CharField(blank=True, max_length=255, null=True, verbose_name='ГЛОНАСС')),
                ('bluetooth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth')),
                ('audio_output', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудиовыход')),
                ('wifi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wi-Fi')),
                ('usb', models.CharField(blank=True, max_length=255, null=True, verbose_name='USB')),
                ('nfc', models.CharField(blank=True, max_length=255, null=True, verbose_name='NFC')),
                ('battery_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип аккумулятора')),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Емкость аккумулятора')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
                ('wireless_charger', models.CharField(blank=True, max_length=255, null=True, verbose_name='Беспроводная зарядка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
