# Generated by Django 3.2.6 on 2021-08-10 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_smartwatches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Smartwatches',
            new_name='Smartwatch',
        ),
    ]
