# Generated by Django 3.2.6 on 2021-08-10 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_smartwatches_smartwatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('market_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок')),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер экрана')),
                ('screen_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип экрана')),
                ('screen_technology', models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология экрана')),
                ('screen_resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешение экрана')),
                ('os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Версия операционной системы')),
                ('ram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оперативная память')),
                ('flash_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Флэш-память')),
                ('built_in_camera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная камера')),
                ('body_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса')),
                ('body_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет корпуса')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина')),
                ('thickness', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толщина')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('touch_screen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сенсорный экран')),
                ('screen_backlight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсветка экрана')),
                ('support_txt_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка текстовых форматов')),
                ('support_photo_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка фото форматов')),
                ('support_audio_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка аудио форматов')),
                ('support_archive', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка архивов')),
                ('support_video_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка видео форматов')),
                ('memory_card_support', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поддержка карт памяти')),
                ('sound_recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='Запись звука')),
                ('built_in_speaker', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенный динамик')),
                ('built_in_microphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенный микрофон')),
                ('bluetooth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth')),
                ('audio_output', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудиовыход')),
                ('wifi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wi-Fi')),
                ('modem_3g', models.CharField(blank=True, max_length=255, null=True, verbose_name='3G-модем')),
                ('usb', models.CharField(blank=True, max_length=255, null=True, verbose_name='USB')),
                ('battery_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип аккумулятора')),
                ('battery_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Емкость аккумулятора')),
                ('battery_life', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время автономной работы')),
                ('charging_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время зарядки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
