# Generated by Django 3.2.6 on 2021-08-11 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('connection_interface', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интерфейс подключения мыши')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('appointment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назначение')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер мыши')),
                ('sensor_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип сенсора')),
                ('sensor_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель сенсора')),
                ('max_sensor_resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальное разрешение сенсора')),
                ('max_polling_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальная частота опроса')),
                ('body_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса')),
                ('backlight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсветка')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('wire_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина провода')),
                ('variable_resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изменяемое разрешение')),
                ('built_in_memory', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенная память')),
                ('response_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время отклика')),
                ('number_of_buttons', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество кнопок')),
                ('number_of_scroll_wheels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество колёс прокрутки')),
                ('scroll_wheel_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип колеса прокрутки')),
                ('wire_braid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оплетка провода')),
                ('quiet_click', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тихий клик')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина')),
                ('height', models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
