# Generated by Django 3.2.6 on 2021-08-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_keyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('compatibility', models.CharField(blank=True, max_length=255, null=True, verbose_name='Совместимость')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал поверхности')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('sideboard', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бортик')),
                ('functional_features', models.CharField(blank=True, max_length=255, null=True, verbose_name='Функциональные особенности')),
                ('cable_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина кабеля')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('depth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубина')),
                ('thickness', models.CharField(blank=True, max_length=255, null=True, verbose_name='Толщина')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
