# Generated by Django 3.2.6 on 2021-08-11 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_mat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('appointment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назначение')),
                ('view', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид')),
                ('wireless_interface', models.CharField(blank=True, max_length=255, null=True, verbose_name='Беспроводной интерфейс')),
                ('body_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Материал корпуса')),
                ('pop_filter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поп-фильтр')),
                ('microphone_jack', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разъем(-ы) на микрофоне')),
                ('connector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разъем(-ы) подключения')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('focus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направленность')),
                ('variable_focus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изменяемая направленность')),
                ('sampling_frequency', models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота дискретизации')),
                ('bottom_frequency_range_boundary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Нижняя граница частотного диапазона')),
                ('top_frequency_range_boundary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Верхняя граница частотного диапазона')),
                ('diaphragm_diameter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диаметр диафрагмы')),
                ('signal_to_noise_ratio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соотношение сигнал/шум')),
                ('sensitivity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Чувствительность')),
                ('spl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Макс. уровень звукового давления (SPL)')),
                ('coefficient_harmonic_distortion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Коэф. гармонических искажений')),
                ('microphone_indication', models.CharField(blank=True, max_length=255, null=True, verbose_name='Индикация на микрофоне')),
                ('cable_length', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длина кабеля')),
                ('headphone_out', models.CharField(blank=True, max_length=255, null=True, verbose_name='Выход на наушники')),
                ('control_elements', models.CharField(blank=True, max_length=255, null=True, verbose_name='Элементы управления')),
                ('microphone_power', models.CharField(blank=True, max_length=255, null=True, verbose_name='Питание микрофона')),
                ('backlight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсветка')),
                ('usb', models.CharField(blank=True, max_length=255, null=True, verbose_name='USB для периферии')),
                ('digital_effects', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цифровые эффекты')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
