# Generated by Django 3.2.6 on 2021-08-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_tablet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('market_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода на рынок')),
                ('diagonal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Диагональ')),
                ('aspect_ratio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соотношение сторон')),
                ('resolution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Разрешение')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип')),
                ('matrix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Матрица')),
                ('curved_screen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изогнутый экран')),
                ('bending_radius', models.CharField(blank=True, max_length=255, null=True, verbose_name='Радиус изгиба')),
                ('screen_refresh_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Частота обновления экрана')),
                ('flicker_free', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отсутствие мерцания (Flicker-free)')),
                ('body_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет корпуса')),
                ('stand_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет подставки')),
                ('hdr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Расширенный динамический диапазон (HDR)')),
                ('screen_surface', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поверхность экрана')),
                ('touch_screen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сенсорный экран')),
                ('dynamic_refresh_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Динамическая частота обновления экрана')),
                ('frame_sync_technology', models.CharField(blank=True, max_length=255, null=True, verbose_name='Технология синхронизации кадров')),
                ('brightness', models.CharField(blank=True, max_length=255, null=True, verbose_name='Яркость')),
                ('contrast', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контрастность')),
                ('srgb', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цветовой охват sRGB')),
                ('dci_p3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цветовой охват DCI-P3')),
                ('gtg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время отклика (GtG)')),
                ('horizontal_viewing_angle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Угол обзора по горизонтали')),
                ('vertical_viewing_angle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Угол обзора по вертикали')),
                ('power_supply', models.CharField(blank=True, max_length=255, null=True, verbose_name='Блок питания')),
                ('built_in_speakers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Встроенные динамики')),
                ('camera', models.CharField(blank=True, max_length=255, null=True, verbose_name='Камера')),
                ('microphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Микрофон')),
                ('frameless_design', models.CharField(blank=True, max_length=255, null=True, verbose_name='Безрамочный дизайн')),
                ('mhl', models.CharField(blank=True, max_length=255, null=True, verbose_name='MHL')),
                ('bluetooth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth')),
                ('wifi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Wi-Fi')),
                ('connection_interface', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интерфейс подключения')),
                ('headphone_out', models.CharField(blank=True, max_length=255, null=True, verbose_name='Выход на наушники')),
                ('usb', models.CharField(blank=True, max_length=255, null=True, verbose_name='USB')),
                ('hdmi', models.CharField(blank=True, max_length=255, null=True, verbose_name='HDMI')),
                ('ethernet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ethernet')),
                ('vesa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Крепление VESA')),
                ('turn_left_right', models.CharField(blank=True, max_length=255, null=True, verbose_name='Поворот вправо-влево')),
                ('portrait_mode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Портретный режим')),
                ('max_screen_tilt_angle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный угол наклона экрана')),
                ('width', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('depth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Глубина')),
                ('height', models.CharField(blank=True, max_length=255, null=True, verbose_name='Высота')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
